title: Your awesome title
description:
baseurl: ""
url: ""

permalink: pretty

# Collections
collections:
  authors:
    ouput: false
  categories:
    output: true
    layout: category
    permalink: "/blog/:title/"


# Default Settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      type: website
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:categories/:title/"
      author: ben
      type: article
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"


# Sass
#sass:
#  sass_dir: _scss
#  style: compressed

# Assets
assets:
  compress:
    css: true
    html: true
  digest: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-assets
  - mini_magick
exclude:
  - Gemfile
  - Gemfile.lock
