title: Company Name
description:
baseurl: ""
url: "http://russet-parsnip.cloudvent.net"

permalink: pretty

# Collections
collections:
  authors:
    ouput: false
  categories:
    output: true
    layout: category
    permalink: "/blog/:title/"


# Default Settings
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      type: website
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:categories/:title/"
      author: ben
      type: article
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"


# Sass
sass:
  sass_dir: _scss
  style: compressed

# Assets
assets:
  compress:
    css: true
  digest: true
  sources:
    - _assets/css
    - uploads
  assets:
    - "*.png"
    - "*.jpg"
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-sitemap
  - mini_magick
  - jekyll-assets
  - autoprefixer-rails
exclude:
  - Gemfile
  - Gemfile.lock
