title: Your awesome title
description:
baseurl: ""
url: ""

# Authors
#authors:
#  ben:
#    name: Ben Cunningham
#  stephen:
#    name: Stephen Walsh

# Collections
collections:
  authors:
    ouput: false
  categories:
    output: true
    permalink: "/blog/:title.html"
    layout: category

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: ben
  -
    scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

# Sass
sass:
  sass_dir: _scss
  style: compressed

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
